<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 STRICT//EN" "DTD/xhtml1-strict.dtd">
<html>
<head>
<title>Microchip TCP/IP Stack Demo App</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body onLoad="allowAJAX=true;" onUnload="allowAJAX=false;">
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 5px 5px"><img src="/mchp.gif" /></div>

<div id="title"><div class="right">TCP/IP Stack Demo Application</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="/index.htm">Overview</a>
<a href="/dynvars.htm">Dynamic Variables</a>
<a href="/forms.htm">Form Processing</a>
<a href="/auth.htm">Authentication</a>
<a href="/cookies.htm">Cookies</a>
<a href="/upload.htm">File Uploads</a>
<a href="/email">Send E-mail</a>
<a href="/protect/config.htm">Configuration</a>
</div>